---
functional:
  - Навигация содержит ссылки на корзину, каталог, лого и переключение языков. Присуствует на всех экранах
  - Футер содержит правовую информацию и версию, присутсвует на всех экранах.
  - В каталоге за раз показываем не больше 30 товаров, есть кнопки для пролистывания вперед-назад.
  - В каталолге пользователь должен иметь возможность фильтровать и искать товары по ключевому слову, бренду, цене и наличию.
  - В каталоге карточка товара содержит фото, название, цена со скидкой и без, количеством на складе и кнопку Добавить.
  - По нажатию на Добавить в карточке добавляется в корзину, счетчик товаров увеличиваеся на 1, остаемся в каталоге товаров.
  - По нажатию на карточку открывается экран товара.
  - На экране товара есть фото (может быть несколько), название, хештег (опционально), рейтинг, цена со скидкой и без, % скидки, описание, артикул и кнопка Добавить. 
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - На экране корзины можно продолжить покупки, очистить корзину и посмотреть полную стоимость корзины.
  - На экране корзины кнопка Проверить откроет попап со списком, количеством, ценами, полной стоимостью, крестиком и кнопкой Закрыть можно закрыть попап.
  - На экране корзины для каждого товара есть название товара, количество на складе, добавленное количество, цена со скидкой и без, кнопка удалить.
  - Корзина хранится в сессии браузера.
  - Страница не должна перезагружаться при работе с сайтом.
  - Сайт должен иметь мобильную версию.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Верстка между брейкпоинтами должна быть адаптивной.
  - Нет некрасивостей - битых картинок, съехавшего текста и тп.
  - Должно быть и интуитивно понятно.
  - Доступны 2 языка интерфейса русский и английский. Верстка не едет при переключении.
  - Успешная и неуспешная оплата должна корректно обрабатываться.
  - Ошибки соединения или бекенда должны обрабатываться.
  - Можно смотреть только свою корзину.
  - Нельзя зарегистрировать двух одинаковых пользователей.
  - Товары не слетают при закрытии вкладки браузера. Кука не сессионная.
  - Нельзя добавить некорректные товары (два одинаковых товара с одинаковой ценой, с отрицательной ценой, без названия и тп).
  
