---
functional:
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без.
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Если список товаров большой - выводим постранично.
  - Пользователь должен иметь возможность фильтровать товары.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - На странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты.
  - Корзина хранится в сессии браузера.
  - Страница не должна перезагружаться при работе с сайтом.
  - Сайт должен иметь мобильную версию.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Верстка между брейкпоинтами должна быть адаптивной.
  - Успешная и неуспешная оплата должна корректно обрабатываться.
  - Ошибки соединения или бекенда должны обрабатываться.
  - Можно смотреть только свою корзину.
  - Нельзя зарегистрировать двух одинаковых пользователей.
  - Товары не слетают при закрытии вкладки браузера. Кука не сессионная.
  - Нельзя добавить некорректные товары (два одинаковых товара с одинаковой ценой, с отрицательной ценой, без названия и тп).
